# > Anti_ISP_JavaScript_Injection
^https?:\/\/c.minisplat.cn - reject
^https?:\/\/c1.minisplat.cn - reject
^https?:\/\/cache.changjingyi.cn - reject
^https?:\/\/cache.gclick.cn - reject

# > Anti_ISP_Safari_Baidu_CPM_Hijack
^https?:\/\/m.coolaiy.com\/b.php - reject
^https?:\/\/www.babyye.com\/b.php - reject
^https?:\/\/www.gwv7.com\/b.php - reject
^https?:\/\/www.likeji.net\/b.php - reject

# > 新浪
^https?:\/\/api.weibo.cn\/2\/statuses\/extend\?gsid= - reject
^https?:\/\/edit.sinaapp.com\/ua\?t=adv - reject
^https?:\/\/free.sinaimg.cn\/u1.img.mobile.sina.cn - reject
^https?:\/\/simg.s.weibo.com\/.+_ios\d{2}.gif - reject
^https?:\/\/storage.wax.weibo.com\/\w+.(png|jpg|mp4) - reject
^https?:\/\/u1.img.mobile.sina.cn\/public\/files\/image\/\d{3}x\d{2,4}.+(png|jpg|mp4) - reject

# > 知乎
^https?:\/\/api.zhihu.com\/ab\/api - reject
^https?:\/\/api.zhihu.com\/ad-style-service - reject
^https?:\/\/api.zhihu.com\/app_config - reject
^https?:\/\/api.zhihu.com\/appview\/api\/v4\/answers.+recommendations - reject
^https?:\/\/api.zhihu.com\/banner - reject
^https?:\/\/api.zhihu.com\/launch - reject
^https?:\/\/api.zhihu.com\/market\/popover - reject
^https?:\/\/api.zhihu.com\/real_time - reject
^https?:\/\/api.zhihu.com\/search\/preset_words - reject
^https?:\/\/api.zhihu.com\/search\/top_search - reject
^https?:\/\/api.zhihu.com\/zst\/events - reject
^https?:\/\/www.zhihu.com\/api\/v4\/community-ad\/ - reject
^https?:\/\/www.zhihu.com\/terms\/privacy\/confirm - reject

# > 追书神器
^https?:\/\/(api|b).zhuishushenqi.com\/advert - reject
^https?:\/\/api.zhuishushenqi.com\/notification\/shelfMessage - reject
^https?:\/\/api.zhuishushenqi.com\/recommend - reject
^https?:\/\/api.zhuishushenqi.com\/splashes\/ios - reject
^https?:\/\/api01pbmp.zhuishushenqi.com\/gameAdvert - reject
# > Upgrade
^https?:\/\/api.zhuishushenqi.com\/user\/bookshelf-updated - reject
^https?:\/\/itunes.apple.com\/lookup\?id=575826903 - reject

# > 喜马拉雅
^https?:\/\/adse.+.com\/[a-z]{4}\/loading\?appid= - reject
^https?:\/\/adse.ximalaya.com\/ting\/feed\?appid= - reject
^https?:\/\/adse.ximalaya.com\/ting\/loading\?appid= - reject
^https?:\/\/adse.ximalaya.com\/ting\?appid= - reject
^https?:\/\/fdfs.xmcdn.com\/group21\/M03\/E7\/3F\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group21\/M0A\/95\/3B\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group22\/M00\/92\/FF\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group22\/M05\/66\/67\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group22\/M07\/76\/54\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group23\/M01\/63\/F1\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group23\/M04\/E5\/F6\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group23\/M07\/81\/F6\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group23\/M0A\/75\/AA\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group24\/M03\/E6\/09\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group24\/M07\/C4\/3D\/ - reject
^https?:\/\/fdfs.xmcdn.com\/group25\/M05\/92\/D1\/ - reject

# > 掌阅
^https?:\/\/book.img.ireader.com\/group6\/M00 - reject