^https?:\/\/ulogs\.umeng\.com - reject
^https?:\/\/mi\.gdt\.qq\.com\/gdt_mview.fcg - reject
^https?:\/\/raddus\.bayescom\.com\/raddusg - reject
^https?:\/\/eleven\.bayescom\.cn\/eleven - reject
^https?:\/\/api-access\.pangolin-sdk-toutiao\.com\/api\/ad\/* - reject
^https?:\/\/sdk\.e\.qq\.com\/getad - reject
^https?:\/\/*\.xdrig\.com - reject